# Generated by Django 4.1.7 on 2023-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
