# Generated by Django 4.1.7 on 2023-04-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_spot_latutude_alter_spot_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='latutude',
            new_name='latitude',
        ),
    ]
