# Generated by Django 4.1.7 on 2023-04-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spot_images'),
        ),
    ]
